### ISSUE TITLE
refactoring country labels

### ISSUE THREAD

**Issue by systats** [srfdata/2017-01-dual-use#1]
Hey guys: great talk at useR!2017 and you are doing a very interesting work. I have a lot to explore in the future :) Have you checked out the package countrycode https://github.com/vincentarelbundock/countrycode for cleaning up noisy country labels? In political Science and Econometrics it helps a lot to merge panel data.

Best regards
Simon

**Comment by grssnbchr** [comment]
Thank you and thanks for the tip - will have a look into it!
